name: Auto I18n Migration

on:
  workflow_dispatch:
    inputs:
      i18n_plus_repo:
        description: 'Repo of i18n-plus tools (format: owner/repo)'
        required: true
        default: 'obsidian-plugins-i18n-plus'
      target_main_file:
        description: 'Path to main.ts'
        required: true
        default: 'src/main.ts'

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Target Repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Checkout i18n-plus Tools
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.i18n_plus_repo }}
          path: _i18n_tools

      - name: Copy Adapter
        run: |
          # Detect source folder
          SRC_DIR=$(dirname ${{ inputs.target_main_file }})
          mkdir -p $SRC_DIR/lang
          
          # Copy generic adapter from i18n-plus tools
          if [ -f "_i18n_tools/templates/adapter.ts" ]; then
            cp _i18n_tools/templates/adapter.ts $SRC_DIR/lang/i18n.ts
            echo "✅ Adapter successfully copied."
          else
            echo "❌ Error: _i18n_tools/templates/adapter.ts not found."
            exit 1
          fi

      - name: Install jscodeshift
        run: npm install -g jscodeshift typescript

      - name: Inject Initialization Code
        run: |
          jscodeshift -t _i18n_tools/scripts/inject-i18n.cjs ${{ inputs.target_main_file }} --parser=ts --run-in-band

      - name: Replace Strings (Codemod)
        run: |
          jscodeshift -t _i18n_tools/scripts/i18n-codemod.cjs ${{ inputs.target_main_file }} --parser=ts --run-in-band
          # You can add more files/directories here like:
          # jscodeshift -t _i18n_tools/scripts/i18n-codemod.cjs src/ --parser=ts --run-in-band

      - name: Extract Keys
        run: |
          SRC_DIR=$(dirname ${{ inputs.target_main_file }})
          node _i18n_tools/scripts/extract-keys.cjs $SRC_DIR

      - name: Format Code
        run: |
          # Try to run prettier if it exists in the project
          if npx --no-install prettier --version >/dev/null 2>&1; then
             npx prettier --write "${{ inputs.target_main_file }}"
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: 'refactor: Auto-migrate to i18n-plus'
          body: |
            This PR was automatically generated by i18n-plus migration workflow.
            
            Changes:
            - Injected i18n adapter (`lang/i18n.ts`).
            - Initialized i18n in `main.ts`.
            - Automated string replacement with `t()`.
            - Generated default `en.ts` locales.
            
            **Action Required**:
            - Review dynamic strings (template literals).
            - Check arrays and complex DOM creations.
          branch: refactor/i18n-plus-migration
