/**
 * i18n-plus Key Extractor
 * 
 * Scans source code for all t('key') calls, extracts keys, and generates an en.ts locale file.
 * 
 * Usage: node scripts/extract-keys.cjs src/
 */

const fs = require('fs');
const path = require('path');

// Simple Regex: Matches .t("STRING") or .t('STRING')
// Group 1: Quote type
// Group 2: Key content
const REGEX_T_CALL = /\.t\(\s*(['"`])((?:[^\\\1]|\\.)*?)\1/g;

// Recursively traverse directory
function walkDir(dir, callback) {
    fs.readdirSync(dir).forEach(f => {
        let dirPath = path.join(dir, f);
        let isDirectory = fs.statSync(dirPath).isDirectory();
        if (isDirectory) {
            walkDir(dirPath, callback);
        } else {
            callback(path.join(dir, f));
        }
    });
}

function extractKeys(srcDir) {
    const keys = new Set();

    walkDir(srcDir, (filePath) => {
        if (!filePath.endsWith('.ts') && !filePath.endsWith('.tsx')) return;

        const content = fs.readFileSync(filePath, 'utf-8');
        let match;
        while ((match = REGEX_T_CALL.exec(content)) !== null) {
            const key = match[2]; // Get key content
            // Handle escaped characters
            const cleanKey = key.replace(/\\(['"`])/g, '$1');
            keys.add(cleanKey);
        }
    });

    return Array.from(keys).sort();
}

function generateLocaleFile(keys, outputPath) {
    const lines = [];
    lines.push('// Generated by i18n-plus key extractor');
    lines.push('export default {');
    keys.forEach(key => {
        // Simply use key as value for generating JS code
        // Note: handle quotes in key
        const safeKey = JSON.stringify(key);
        lines.push(`    ${safeKey}: ${safeKey},`);
    });
    lines.push('};');

    // Ensure directory exists
    const dir = path.dirname(outputPath);
    if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
    }

    fs.writeFileSync(outputPath, lines.join('\n'));
    console.log(`✅ Extracted ${keys.length} keys to ${outputPath}`);
}

const targetDir = process.argv[2] || 'src';
const extractedKeys = extractKeys(targetDir);

// Infer or read output path
let outputPath = process.argv[3];
if (!outputPath) {
    // If targetDir looks like "path/to/src", we want "path/to/src/lang/locales/en.ts"
    // If targetDir is just ".", we might guess.
    // For now, let's default to joining.
    outputPath = path.join(targetDir, 'lang', 'locales', 'en.ts');
}

generateLocaleFile(extractedKeys, outputPath);
